# Generated by Django 5.2.13 on 2026-05-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_farm_delete_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='farm',
            table='Farms',
        ),
    ]
