# Generated by Django 5.2.13 on 2026-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_farm_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
