# Generated by Django 5.2.13 on 2026-05-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('municipality', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=150)),
                ('result_type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('api_status_code', models.IntegerField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SearchErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('status_code', models.IntegerField()),
                ('error_type', models.IntegerField()),
                ('error_description', models.TextField()),
                ('error_response', models.TextField()),
                ('search_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='error_log', to='analysis.searchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PlantAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('susceptible_animal_species', models.TextField()),
                ('human_risks', models.TextField()),
                ('common_symptoms', models.TextField()),
                ('recommended_actions', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.searchrequest')),
            ],
        ),
    ]
