# Generated by Django 5.2.13 on 2026-05-31 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantanalysisresult',
            table='PlantAnalysisResults',
        ),
        migrations.AlterModelTable(
            name='searcherrorlog',
            table='SearchErrorLogs',
        ),
        migrations.AlterModelTable(
            name='searchrequest',
            table='SearchRequests',
        ),
    ]
