# Generated by Django 5.2.13 on 2026-06-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_plantanalysisresult_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='image_path',
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='image',
            field=models.ImageField(default=None, upload_to='analysis/'),
            preserve_default=False,
        ),
    ]
