# Generated by Django 5.2.13 on 2026-06-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_searchrequest_image_path_searchrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalysisresult',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
